/**
 * API
 * API proxy de data subventions
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RepresentantLegal } from './representantLegal';


export interface RepresentantsLegaux { 
    representants_legaux?: Array<RepresentantLegal>;
}

