/**
 * API
 * API proxy de data subventions
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Adresse } from './adresse';
import { UniteLegale } from './uniteLegale';


export interface DonneesEtablissement { 
    activite_principale: object;
    adresse: Adresse;
    adresse_postale_legere: string;
    date_creation: number;
    siret: string;
    tranche_effectif_salarie: object;
    unite_legale: UniteLegale;
}

