/**
 * API
 * API proxy de data subventions
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActivitePrincipale } from './activitePrincipale';
import { FormeJuridique } from './formeJuridique';


export interface UniteLegale { 
    activite_principale: ActivitePrincipale;
    forme_juridique: FormeJuridique;
    personne_morale_attributs: object;
    tranche_effectif_salarie: object;
}

